services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve --watch --force_polling --verbose --livereload --trace
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      # - ./vendor/bundle:/usr/local/bundle