META_KEY_COL = 1
META_VAL_COL = 2
META_MAX_ROW = 9

META_IMPLICIT_GENDER_KEY = "Implicit Gender?"
META_EVENT = "Event"

RESULT_RECORD_ROW = 11
RESULT_TIME_COL = "D"
RESULT_TEAM_COL = "G"
RESULT_GENDER_COL = "H"
RESULT_TIME_RANGE = "{RESULT_TIME_COL}{RESULT_RECORD_ROW}:{RESULT_TIME_COL}".format(
    RESULT_TIME_COL=RESULT_TIME_COL, RESULT_RECORD_ROW=RESULT_RECORD_ROW
)
RESULT_PLACE_TEAM_RANGE = (
    "{RESULT_TEAM_COL}{RESULT_RECORD_ROW}:{RESULT_GENDER_COL}".format(
        RESULT_TEAM_COL=RESULT_TEAM_COL,
        RESULT_RECORD_ROW=RESULT_RECORD_ROW,
        RESULT_GENDER_COL=RESULT_GENDER_COL,
    )
)

# hard-coded for now
DATA_DIR = "data/2022-23/1"
